### ISSUE TITLE
Blog unreadable on some platforms

### ISSUE THREAD

**Issue by andyleap** [Mattias-/Mattias-.github.io#1]
I'm here on firefox on linux, and cannot access your blog.  Maybe change the name to something that's actually RFC1048 compliant?  i.e. '-' is only allowed as an internal character, not a first or last character?

**Comment by Mattias-** [comment]
I added a CNAME so the blog can now be reached at http://blog.ppelgren.se

https://github.com/Mattias-/Mattias-.github.io/commit/4ca8a03c2318ca260343d125ffd400e208f0859b

**Comment by andyleap** [comment]
Works for me, thanks!
